apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: moim
    phase: dev
  name: moiming-dev
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

